---
- name: Install Kubernetes Worker
  hosts: workers
  become: true
  tasks:
    - name: Turning off swap
      shell: |
        swapoff -a
        sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab

    - name: Setting Up Env for containerd
      block:
        - copy:
            content: |
              overlay 
              br_netfilter
            dest: /etc/modules-load.d/containerd.conf 
        - command: modprobe overlay
        - command: modprobe br_netfilter
        - copy:
            content: |
              net.bridge.bridge-nf-call-iptables = 1
              net.ipv4.ip_forward = 1 
              net.bridge.bridge-nf-call-ip6tables = 1 
            dest: /etc/sysctl.d/99-kubernetes-k8s.conf

    - name: Installing containerd
      block:
        - command: sysctl --system
        - apt:
            update_cache: yes
            name: containerd
            state: present

    - name: Configuring containerd
      block:
        - shell: containerd config default | tee /etc/containerd/config.toml >/dev/null 2>&1
        - replace:
            path: /etc/containerd/config.toml
            regexp: 'SystemdCgroup = false'
            replace: 'SystemdCgroup = true'

    - name: Restarting containerd
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    - name: Installing Kubernetes
      block:
        - apt:
            update_cache: yes
            name:
              - gnupg
              - gnupg2 
              - curl 
              - software-properties-common 
            state: present

    - name: Remove existing Kubernetes apt keyring gpg
      shell: rm -f /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes apt keyring gpg
      shell: curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg

    - name: Add Kubernetes list to sources.list.d directory
      copy:
          content: 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /'
          dest: /etc/apt/sources.list.d/kubernetes.list

    - name: Install Kubernetes components on worker nodes
      block:
        - apt:
            update_cache: yes
            name:
              - kubelet 
              - kubeadm 
              - kubectl 
            state: present

    - name: Hold Kubernetes components at their current version, not to be upgraded by apt upgrade.
      command: apt-mark hold kubelet kubeadm kubectl

    - name: Joining control plane
      shell: $(cat /kube/shared/join_command.txt)
