- name: Install Java and Kafka on Kafka nodes
  hosts: all
  become: true
  gather_facts: true
  vars:
    kafka_version: "3.4.0"
    zookeeper_version: "3.8.0"
    kafka_path: "/kafka"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install OpenJDK
      apt:
        name: openjdk-11-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: Create Kafka directory
      file:
        path: "{{ kafka_path }}"
        state: directory
        owner: vagrant
        group: vagrant

    - name: Download and extract Kafka
      unarchive:
        src: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_2.12-{{ kafka_version }}.tgz"
        dest: "{{kafka_path}}"
        remote_src: yes
        extra_opts: "--strip-components=1"
      notify: Restart Kafka
      become_user: vagrant

    - name: Create Kafka data directory
      file:
        path: "/var/lib/kafka/data"
        state: directory
        owner: vagrant
        group: vagrant

    - name: Copy server.properties
      copy:
        src: files/server-{{kafka_node_id}}.properties
        dest: "{{kafka_path}}/config/server.properties"
        owner: vagrant
        group: vagrant

    - name: Start Kafka Server
      become: yes
      shell: nohup ./bin/kafka-server-start.sh config/server.properties > "{{kafka_path}}/kafka.log" 2>&1 &
      args:
        chdir: "{{kafka_path}}"
      become_user: vagrant


      
  handlers:
    - name: Restart Kafka
      shell: "systemctl restart kafka"
      async: 60
      poll: 0
  
