# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Change this to accomodate your architecture.
  host_architecture = 'arm'
  # Set the box based on the host architecture
  if host_architecture == 'arm'
    config.vm.box = "bento/debian-11-arm64" # ARM Based
  else
    config.vm.box = "bento/debian-11" # Intel Based
  end
  # config.vm.box = "bento/debian-11-arm64" # <-- ARM Based
  # config.vm.box = "bento/debian-11" # <-- Intel Based
  
  # Create ZooKeeper node
  config.vm.define "zookeeper" do |node|
    node.vm.hostname = "zookeeper"
    node.vm.network "private_network", ip: "192.168.50.11"

    node.vm.provider "parallels" do |v|
      v.name = "zookeeper"
      v.memory = 2048
      v.cpus = 2
    end

    node.vm.provision "ansible" do |ansible|
      ansible.playbook = "zookeeper_playbook.yml"
    end
  end

  # Create Kafka nodes
  (1..3).each do |i|
    config.vm.define "kafka#{i}" do |node|
      node.vm.hostname = "kafka#{i}"
      node.vm.network "private_network", ip: "192.168.50.#{i + 20}"

      node.vm.provider "parallels" do |v|
        v.name = "kafka#{i}"
        v.memory = 2048
        v.cpus = 2
      end

      node.vm.provision "ansible" do |ansible|
        ansible.playbook = "kafka_playbook.yml"
        ansible.extra_vars = {
          kafka_node_id: i,
          kafka_zookeeper_connect: "192.168.50.11:2181",
          provision_files_path: "../files"
        }
      end
    end
  end
end