- name: Install ZooKeeper
  hosts: all
  become: true
  gather_facts: true

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install ZooKeeper
      apt:
        name: zookeeperd
        state: present
      when: ansible_os_family == "Debian"

    - name: Start ZooKeeper service
      service:
        name: zookeeper
        state: started
        enabled: true
